### ISSUE TITLE
Public and Private Route 53 with same name. 

### ISSUE THREAD

**Issue by nickkadams** [aws-samples/aws-lambda-ddns-function#24]
We have 2 Route 53 domains (public and private) that share the same TLD name. The lambda function works, but always updates the public zone only. I only want to update the private zone. I was curious if this was on a feature roadmap before I considered any refactor or code removal for my use case. Thanks!

**Comment by spatronis** [comment]
I see that this issue was just closed 5 days ago, but this just came up for me.
We are having the same issue with two hosted zones (one private and one public) sharing the same TLD.  Only the public hosted zone is getting updated.  Is there a way to pin it to the private hosted zone only?

**Comment by spatronis** [comment]
Now that I am digging around, I see that this scenario may be covered by:
https://github.com/aws-samples/aws-lambda-ddns-function/pull/12
