### ISSUE TITLE
Don't create reverse lookup zone for CNAME instances

### ISSUE THREAD

**Issue by akamustang** [aws-samples/aws-lambda-ddns-function#27]
I'm using CNAME tags only but an unused route 53 zone called `0.10.in-addr.arpa.` has been created.

**Comment by akamustang** [comment]
@fadeev2010 Thanks for the suggestion, however I have them setup this way, so it's still an issue.

**Comment by jicowan** [comment]
The function is written to automatically create a reverse lookup zone.  It's for historical reasons.  I originally wrote this to support EMR with custom domain names which required reverse lookup zones.
